name: resume
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-142.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  swipeable_page_route: ^0.4.0

  flutter_svg: ^2.0.7

  logger: ^2.0.2

  # StateManager + DI
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0
  dropdown_button2: ^3.0.0-beta.7

  balanced_text: ^0.0.3

  # Yandex Login
  flutter_login_yandex: ^0.0.4

  # Google Login
  google_sign_in: ^6.1.6
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
