name: resume
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-142.0.dev <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  logger: ^2.0.2

  # StateManager + DI
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
